[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "linqs-quiz-generator"
version = "0.0.1"
description = "A tool that can generate both Canvas quizzes and LaTeX pdfs from a common configuration."
readme = "README.md"
requires-python = ">=3.10"
license = {file = "LICENSE"}

authors = [
    {name = "Eriq Augustine", email = "eaugusti@ucsc.edu"},
]

keywords = ['education', 'quiz', 'canvas']
classifiers = [
    'Intended Audience :: Education',
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python :: 3.10',
]

dependencies = [
    "GitPython>=3.1",
    "lark>=1.1.8",
    "requests>=2.31.0",
]

[project.urls]
Homepage = "https://github.com/eriq-augustine/linqs-quiz-generator"
Repository = "https://github.com/eriq-augustine/linqs-quiz-generator"
